version: '3'

services:
  redis:
    image: redis:3.2.11-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
volumes:
  redis-data:
  elasticsearch-data: